### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getMediaContent()

### ISSUE THREAD

**Issue by EngDjango** [sakebook/flutter_native_ads#54]
`E/AndroidRuntime( 5612): java.lang.NoSuchMethodError: No virtual method getMediaContent()
Lcom/google/android/gms/ads/formats/UnifiedNativeAd$MediaContent; in class Lcom/google/android/gms/ads/formats/UnifiedNativeAd; or its super classes (declaration of 'com.google.android.gms.ads.formats.UnifiedNativeAd' appears in /data/app/com--------------------------==/base.apk)
E/AndroidRuntime( 5612): 	at sakebook.github.com.native_ads.UnifiedAdLayout.ensureUnifiedAd(UnifiedAdLayout.kt:94)
E/AndroidRuntime( 5612): 	at sakebook.github.com.native_ads.UnifiedAdLayout.access$ensureUnifiedAd(UnifiedAdLayout.kt:18)
E/AndroidRuntime( 5612): 	at sakebook.github.com.native_ads.UnifiedAdLayout$2.onUnifiedNativeAdLoaded(UnifiedAdLayout.kt:44)
E/AndroidRuntime( 5612): 	at com.google.android.gms.internal.ads.zzafe.zza(com.google.android.gms:play-services-ads-lite@@19.1.0:6)
E/AndroidRuntime( 5612): 	at com.google.android.gms.internal.ads.zzbzm.zzakv(com.google.android.gms:play-services-ads@@19.1.0:179)
E/AndroidRuntime( 5612): 	at com.google.android.gms.internal.ads.zzbzp.run(Unknown Source:2)
E/AndroidRuntime( 5612): 	at android.os.Handler.handleCallback(Handler.java:789)
E/AndroidRuntime( 5612): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime( 5612): 	at com.google.android.gms.internal.ads.zzdns.zzb(com.google.android.gms:play-services-ads-lite@@19.1.0:9)
E/AndroidRuntime( 5612): 	at com.google.android.gms.internal.ads.zzawu.zzb(com.google.android.gms:play-services-ads@@19.1.0:8)
E/AndroidRuntime( 5612): 	at com.google.android.gms.internal.ads.zzdns.dispatchMessage(com.google.android.gms:play-services-ads-lite@@19.1.0:7)
E/AndroidRuntime( 5612): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 5612): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/AndroidRuntime( 5612): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5612): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime( 5612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by kumar-aakash86** [comment]
Any solution for this. I am also facing the same issue.

**Comment by benjamin-kraatz** [comment]
Same here. Using version 0.4.0.
Upgrading to `0.5.0` fixes it

**Comment by firefoxqb** [comment]
Upgrading to 0.5.0 worked, but now minSdkVersion needs to be changed from 16 to 21.  Is this actually required? My project requires minSdkVersion to less than 21.
